export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <h4>
          <a href="/">Home</a>
        </h4>
        <h4>
          <a href="/vip_buyer">Vip_buyers</a>
        </h4>
        <h4>
          <a href="/lp-bestbuys">lp-bestbuys</a>
        </h4>
        {children}
      </body>
    </html>
  );
}
